"""empty message

Revision ID: 5b7bd7bc2404
Revises: d100af14fb12
Create Date: 2016-02-17 23:10:42.409003

"""

# revision identifiers, used by Alembic.
revision = '5b7bd7bc2404'
down_revision = 'd100af14fb12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('maiden_surname', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'maiden_surname')
    ### end Alembic commands ###
