"""empty message

Revision ID: a7d315c7ea73
Revises: a43aeb3ad0bf
Create Date: 2016-04-16 19:37:07.474736

"""

# revision identifiers, used by Alembic.
revision = 'a7d315c7ea73'
down_revision = 'a43aeb3ad0bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legend', sa.Column('title', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legend', 'title')
    ### end Alembic commands ###
